### ISSUE TITLE
如何进行部署使用

### ISSUE THREAD

**Issue by Maxxiecook** [zhangxiangliang/stock-api#1]
RT 环境要求是什么  需要使用什么操作系统 谢谢

**Comment by zhangxiangliang** [comment]
使用环境本人使用的是 `node v12.18.2` 版本作为开发，不过项目编译输出为 `es5` 应该没有版本限制，操作系统应该也是都可以使用。

本项目主要是对接口做了统一的处理，目标主要是用在 JavaScript 和 TypeScript 项目。可以直接导入前端项目中通过调用数据并配合 vue、react 等框架输出展示互数据，也可以用于 VSCode 插件、命令行脚本。

## 第一步 - 安装代码包

```
yarn add stock-api
```

## 第二步 - 导入数据源并调用相关接口

现在支持: 网易财经、雪球、新浪股票、腾讯股票，这里举例使用新浪数据源：

```
import { stocks } from "stock-api";

// 数据源
const sina = stocks.sina;

// 获取股票组实时数据
stocks.sina.searchStocks(["510500"]).then(console.log);

// 获取股票实时数据
stocks.sina.getStock("SH510500").then(console.log);

// 获取股票组实时数据
stocks.sina.searchStocks(["510500"]).then(console.log);
```

**Comment by liyangphp** [comment]
跨域问题

**Comment by weekdawn** [comment]
跨域了

**Comment by cjh-store** [comment]
跨域

**Comment by weekdawn** [comment]
您发的信件我已收到！                                 周黎明（weekdawn）This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by zhoustudent** [comment]
所以想问下现在跨域问题解决了嘛？

**Comment by zhangxiangliang** [comment]
这个用在后端，所以没做跨域的处理。
